spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  context-path: /backend
  port: 8180
management:
  security:
    enabled: false

eureka:
  instance:
    home-page-url-path: ${server.context-path:/}
    statusPageUrlPath: ${server.context-path:}/info
    healthCheckUrlPath: ${server.context-path:}/health
    non-secure-port: ${server.port}

